# Generated by Django 4.0.6 on 2023-01-09 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='first_assign_user',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='first_assignment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='second_assign_user',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='second_assignment',
            field=models.BooleanField(default=False),
        ),
    ]
