# Generated by Django 4.1.4 on 2022-12-23 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='first_assignment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='second_assignment',
            field=models.BooleanField(default=False),
        ),
    ]
