# Generated by Django 4.1.5 on 2023-01-23 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_firstlabeleddata_review_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstlabeleddata',
            name='review_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.review'),
        ),
    ]
