# Generated by Django 4.0.6 on 2023-01-09 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_review_first_assign_user_review_first_assignment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='web_status',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_name', models.TextField(default='')),
                ('status_value', models.TextField(default='')),
            ],
        ),
        migrations.AlterField(
            model_name='review',
            name='first_assign_user',
            field=models.CharField(default='0', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='second_assign_user',
            field=models.CharField(default='0', max_length=10, null=True),
        ),
    ]
