# Generated by Django 4.0.6 on 2023-04-13 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_review_first_assign_user_and_more'),
        ('mainapp', '0003_alter_firstlabeleddata_review_id'),
    ]

    operations = [
    ]
