# Generated by Django 4.0.6 on 2023-01-09 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_web_status_alter_review_first_assign_user_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='web_status',
            new_name='WebStatus',
        ),
    ]
