# Generated by Django 4.0.6 on 2023-06-04 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_merge_20230413_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='model_code',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='model_name',
            field=models.TextField(default='', null=True),
        ),
    ]
