# Generated by Django 4.0.6 on 2023-06-07 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_review_model_code_review_model_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstlabeleddata',
            name='model_code',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='firstlabeleddata',
            name='model_name',
            field=models.TextField(default='', null=True),
        ),
    ]
