# Generated by Django 4.0.6 on 2023-06-10 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='path/to/default_image.jpg', null=True, upload_to='profile/'),
        ),
    ]
