# Generated by Django 4.0.6 on 2023-06-10 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='../mainapp/static/mainapp/image/defalut.png', null=True, upload_to='profile/'),
        ),
    ]
